export type IOrder = {
	id: string;
	adminId: string;
	userId: string;
	orderNo: number;
	items: any[];
	status: number;
	statusCode: string;
	totalCost: number;
	deliveryMethod: any;
	clientId: string;
	customerName: string;
	customerEmail: string;
	customerPhone: string;
	customerAddress: string;
	deliveryLocation: any;
	tableNo: string;
	date: Date;
	dateString: string;
	deliveryDate: Date;
	deliveryDateString: string;
	deliveryTime: string;
	deliverer: string;
	deliveredSignature: any;
	confirmed: boolean;
};
